-- source: https://www.youtube.com/watch?v=vdn_pKJUda8
require("elopez.plugins-setup")
require("elopez.core.options")
require("elopez.core.keymaps")
require("elopez.core.colorscheme")
require("elopez.plugins.nvim-tree")
require("elopez.plugins.comment")
require("elopez.plugins.lualine")
require("elopez.plugins.telescope")
require("elopez.plugins.nvim-cmp")
require("elopez.plugins.lsp.mason")
require("elopez.plugins.lsp.lspsaga")
require("elopez.plugins.lsp.lspconfig")
require("elopez.plugins.lsp.null-ls")
require("elopez.plugins.gitsigns")
require("elopez.plugins.treesitter")
require("elopez.plugins.dap")
